### ISSUE TITLE
Définir la date de l’atelier

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex-frontend#22]
- [x] Créer un Doodle
- [x] Partager le Doodle entre SK et EDM
- [x] Emailer Doodle à JR
- [x] Emailer Doodle à ELB
- [x] Emailer Doodle à SA
- [x] Emailer Doodle à JFL
- [x] Emailer Doodle à JL
- [x] Emailer Doodle à SE et NB (CENR)
- [x] Attendre réponses de tous
- [x] Emailer tous invitation calendrier

**Comment by iolyd** [comment]
@sjinko, voici un _draft_ de courriel pour introduire l'atelier 1:

> Bonjour à tous,
>
> Afin de poursuivre le projet de la plateforme numérique nplex qui vous a été présenté le 8 octobre dernier, nous désirons recueillir des compléments d'information qui pourront nous accompagner dans la définition et l’ajustement des fonctionnalités de l’outil à développer.
> À cet effet, nous vous invitons à participer au premier atelier d’idéation qui se déroulera en présentiel*, au même endroit où prit place la rencontre de démarrage, soit au local 4133 de la Faculté de l’aménagement de l’UdeM. La durée prévue de l’activité est de 1h30. Pour aider à déterminer un moment opportun, nous vous prions d’indiquer vos disponibilités dans le doodle partagé.
>
> *Si pour une raison ou une autre vous ne pouvez pas vous joindre à nous en présentiel, veuillez simplement nous l’indiquer par courriel et nous prévoirons les outils nécessaires pour permettre votre participation à distance.
>
> Bien cordialement,

**Comment by sjinko** [comment]
Très bien. On peut envoyer.
