### ISSUE TITLE
Envoyer lettres d’invitation individuelles

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex-frontend#36]
Salut @iolyd, pourrais-tu préparer des lettres d'invitation du CC à partir du template suivant : https://cirrus.gnp.umontreal.ca/index.php/f/412461

**Comment by iolyd** [comment]
@sjinko, voici une version à valider: https://cirrus.gnp.umontreal.ca/index.php/s/Q4E89PJn5EEkyJm

**Comment by sjinko** [comment]
Salut @iolyd, le texte est très bien. Il y a juste un souci d’affichage de la font dans le pied de page. 
Tu trouveras ici la font Neue Haas : https://cirrus.gnp.umontreal.ca/index.php/s/bTPifWrdQMyx5xc
Si ca ne fonctionne toujours pas, tu peux utiliser Helvetica
