### ISSUE TITLE
Transcrire les post-it atelier 1

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex-frontend#37]
@iolyd, j'ai déposé les post it dans le dossier nplex sur Cirrus

**Comment by iolyd** [comment]
Retranscription complétée:
https://www.figma.com/file/obTuJ89sYcqhxGvzg9bcpc/atelier-1-ideation?node-id=0%3A1

Il reste à «digérer» et synthétiser le tout pour tirer des constats (#30)
