### ISSUE TITLE
Consolider les dossiers sur Cirrus

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex-frontend#38]
Il semble qu’on ai deux dossier sur CIRRUS pour nplex. 
Voici celui auquel j’ai accès: https://cirrus.gnp.umontreal.ca/index.php/f/406882

**Comment by iolyd** [comment]
Après exploration, il semble que le problème n'était pas un dédoublement de dossier, mais plutôt des arborescences personnalisées différentes (un fonctionnement de Nextcloud qui me mélange encore). J'avais initialement renommé le dossier partagé différemment, mais cette modification est appliquée uniquement du point de vue de mon compte. J'ai réorganisé les répertoires pour tenter de restituer la bonne structure de mon bord, en espérant ne pas avoir déplacé ou brisé des choses dans les dossiers originaux.

**Comment by sjinko** [comment]
Voici ce à quoi j‘ai accès dans Cirrus pour ce dossier. Peux-tu me confirmer avoir les mêmes documents?

<img width="1181" alt="Screenshot 2022-01-06 at 17 11 28" src="https://user-images.githubusercontent.com/8132989/148459501-a7b91bd7-1528-49cf-a893-3704f142c1a4.png">

**Comment by iolyd** [comment]
@sjinko Oui, c'est bien ce que j'ai en ce moment:
![image](https://user-images.githubusercontent.com/52970928/148459801-8aedc077-d577-4d35-a607-af859c81bcdc.png)

Je vais y réorganiser le contenu prochainement pour éviter d'avoir des fichiers orphelins
