### ISSUE TITLE
Appel à partenariat

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex-frontend#41]
Compléter et diffuser un appel à partenariat en lien avec la nouvelle proposition de financement partagée par Geneviève (le programme _Partenariat-UdeM_ du Ministère de l'Enseignement Supérieur)

## To do

- [x] Rédiger l'appel, 1 page.
  - Disponible ici: [Appel à partenariat (OneDrive)](https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/Ea86QHBtl8BIg-1CJAr1lr0BqqeyF-FiO8_7Li-DfthfOA?e=vJvO17)
- [x] Faire valider
- [ ] Colliger adresses de partenaires potentiels
- [ ] Envoyer courriels

**Comment by sjinko** [comment]
Salut @iolyd, j‘ai fait quelques modifications. Pourrais-tu:

- [ ] valider
- [ ] passer dans Antidote
- [ ] mettre en page sur le papier à lettre de la Chaire

Pour être réaliste, je pense que nous devrions tout d’abord contacter l’AAPPQ d’ici lundi (je peux m’en charger).

**Comment by iolyd** [comment]
@sjinko C'est bon. Voici le répertoire CIRRUS qui contient la lettre destinée à l'AAPQ https://cirrus.gnp.umontreal.ca/index.php/s/jQ3sTWiW9t4C8WQ

**Comment by sjinko** [comment]
Ok, merci, j’envoie à l’aappq (j’ai modifié le nom des fichiers).

**Comment by sjinko** [comment]
J’ai écrit à G. L-G. pour savoir si le projet d’un financement complémentaire était toujours d’actualité.

**Comment by iolyd** [comment]
Je ferme ce issue en faveur de celui dans le dépôt général: https://github.com/CUPUM/general/issues/108
