### ISSUE TITLE
Préparer et soumettre une proposition de workshop pour congrès 2022 de la SÉAC

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex-frontend#46]
Le _47e congrès annuel de la Société pour l’étude de l’architecture au Canada_ aura lieu du 25 au 28 mai 2022 sous la thématique « _Du renouveau au renouvellement_ » :

[SEAC2022SSAC-CFS.pdf](https://github.com/CUPUM/nplex-frontend/files/7704577/SEAC2022SSAC-CFS.pdf)

Pour y tenir une séance, nous devons soumettre une proposition **avant le 19 décembre**.

### Idéation

L'atelier Nplex pourrait aborder la thématique du congrès sous l'angle des **enjeux pratiques et théoriques**, à savoir les défis dans l'accès à l'information au niveau de l'historique des espaces et bâtiments qui voient de nouveaux projets d'aménagement, l'organisation de cette information en synthèse cohésive, et sa communication via une plateforme web multi-usage.

### Préparation

- [ ] Identifier un angle/sujet en lien avec l'appel
- [ ] Développer une activité pour l'atelier
- [ ] Rédiger la proposition
- [ ] Soumettre à l'adresse seac.2022.ssac@gmail.com

**Comment by iolyd** [comment]
@sjinko, à relire l'appel à propositions en anglais et à regarder les congrès passés de la SÉAC, je crois avoir mal compris ce que les organisateurs entendent par «atelier» dans la version française. Il semble être question de propositions pour des séances (_sessions_ plutôt que _workshops_). Devrions-nous plutôt viser un article en lien avec l'appel qui sera diffusé en janvier?

**Comment by sjinko** [comment]
Il est peut-être un peu tôt pour concevoir une séance pour le 19 décembre. On pourra le faire à l’édition 2023 avec le projet « fonctionnel » et en invitant des projets comparables d’autres universités canadiennes. On pourrait par ailleurs proposer a JP Chupin de présenter sa plateforme des concours.
